<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Microchip TCP/IP Stack Demo App</title>
<link href="/demo/mchp.css" rel="stylesheet" type="text/css" />
<script src="/demo/mchp.js" type="text/javascript"></script>
</head>

<body>
<div id="shadow-one"><div id="shadow-two"><div id="shadow-three"><div id="shadow-four">
<div id="page">

<div style="padding:0 0 65px 5px"><img src="/demo/mchp.gif" alt="Microchip" align="left"/><img src="/demo/harmony.gif" alt="Harmony" align="right"/></div>

<div id="title"><div class="right">TCP/IP Stack Demo Application</div><span id="hello">&nbsp;</span></div>

<div id="menu">
<a href="/demo/index.htm">Overview</a>
<a href="/demo/dynvars.htm">Dynamic Variables</a>
<a href="/demo/forms.htm">Processing Forms</a>
<a href="/demo/auth.htm">Authentication</a>
<a href="/demo/cookies.htm">Cookies</a>
<a href="/demo/upload.htm">Uploading Files</a>
<a href="/demo/email">Sending Emails</a>
<a href="/demo/dyndns">Dynamic DNS</a>
<a href="/demo/protect/config.htm">Network Configuration</a>
<a href="/demo/snmp/snmpconfig.htm">SNMP Configuration</a>
</div>
